{
  "errors": [
    {
      "message": "PrivatePerson 404: Not Found",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "private_persons"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "response": {
          "body": {
            "cause": null,
            "stackTrace": [],
            "deeper": [],
            "message": "PrivatePersonStore#hy-hlo-not-found",
            "suppressed": [],
            "localizedMessage": "PrivatePersonStore#hy-hlo-not-found"
          },
          "url": "http://localhost/ori/api/persons?id=hy-hlo-not-found",
          "status": 404,
          "statusText": "Not Found"
        },
        "exception": {
          "stacktrace": [
            "Error: 404: Not Found",
            "    at h.<anonymous> (/app/dist/index.js:1:3570)",
            "    at Generator.next (<anonymous>)",
            "    at /app/dist/index.js:1:1437",
            "    at new Promise (<anonymous>)",
            "    at i (/app/dist/index.js:1:1182)",
            "    at h.errorFromResponse (/app/dist/index.js:1:3390)",
            "    at h.<anonymous> (/app/dist/index.js:1:3287)",
            "    at Generator.next (<anonymous>)",
            "    at /app/dist/index.js:1:1437",
            "    at new Promise (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": null
}
